# Generated by Django 5.0.3 on 2024-03-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_bd', models.DateTimeField(auto_now=True)),
                ('land_name', models.CharField(max_length=200, verbose_name='Название лендинга')),
                ('land_address', models.CharField(max_length=200, verbose_name='Адрес')),
            ],
        ),
    ]
