# Generated by Django 5.0.3 on 2024-03-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing',
            old_name='land_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='landing',
            old_name='land_bd',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='landing',
            old_name='land_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='landing',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landing',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='landing',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='landing',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, verbose_name='Теги'),
        ),
    ]
