# Generated by Django 5.0.3 on 2024-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landings', '0002_rename_land_address_landing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/')),
            ],
        ),
        migrations.RenameField(
            model_name='landing',
            old_name='data',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='landing',
            name='keywords',
        ),
    ]
